//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortPictures.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SortPictures : global::System.Configuration.ApplicationSettingsBase {
        
        private static SortPictures defaultInstance = ((SortPictures)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SortPictures())));
        
        public static SortPictures Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".jpg, .mov, .mp4")]
        public string ExtensionsToSort {
            get {
                return ((string)(this["ExtensionsToSort"]));
            }
        }
    }
}
